---
title: "Resume" 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




&nbsp;

## Contact
Email: saili "at" ruc "dot" edu "dot" cn

Address: Chongde Building West 713, Renmin University of China, Beijing 100872

Github: https://github.com/saili0103/

&nbsp;



## Education

**Ph.D.**, Department of Statistics and Biostatistics, Rutgers Univeristy, May 2018.

Advisors: Professor [Cun-Hui Zhang](https://stat.rutgers.edu/home/cunhui/) and Professor [Steven Buyske](https://www.stat.rutgers.edu/home/buyske/Home.html).
                   
**Bachelor of Economics**, School of Statistics, Renmin University of China, June 2013.

Exchange student, Department of Statistics and Actuarial Science, University of Hong Kong, Spring 2011.

&nbsp;

## Previous appointment

**Assistant professor** at Institute of Statistics and Big Data, Renmin University of China, September 2021 to August 2022.

**Postdoctoral researcher** at 
Department of Biostatistics, Epidemiology and Informatics, Perelman School of Medicine, University of Pennsylvania, July 2018 to June 2021.

Mentors: Professor [Hongzhe Lee](http://statgene.med.upenn.edu) and Professor [T. Tony Cai](http://www-stat.wharton.upenn.edu/~tcai/).

&nbsp;

## Publications


**Sai Li**. [Debiasing the debiased Lasso with bootstrap]( https://arxiv.org/abs/1711.03613). *Electronic Journal of Statistics*. 14(1): 2298-2337,2020. 

**Sai Li**, T. Tony Cai, and Hongzhe Li. [Inference for high-dimensional linear mixed-effects models: A quasi-likelihood approach](https://arxiv.org/abs/1907.06116). *Journal of the American Statistical Association*. 117(540): 1835-1846, 2022.

**Sai Li**, T. Tony Cai, and Hongzhe Li. [Transfer learning for high-dimensional linear regression: Prediction, estimation, and minimax optimality](https://academic.oup.com/jrsssb/article/84/1/149/7056104). *Journal of the Royal Statistical Society Series B*, 84: 149–173, 2022.

**Sai Li**, T. Tony Cai, and Hongzhe Li. [Transfer learning in large-scale graphical models with false discovery rate control](https://www.tandfonline.com/doi/abs/10.1080/01621459.2022.2044333). *Journal of the American Statistical Association*.118(543), 2171-2183, 2023.

Huaxiu Yao, Yu Wang, **Sai Li**, Linjun Zhang, Weixin Liang, James Zou, and Chelsea Finn. [ Improving out-of-distribution robustness via selective augmentation](https://arxiv.org/abs/2201.00299). *International Conference of Machine Learning*. 2022.

**Sai Li**, Tianxi Cai, and Rui Duan. [Targeting Underrepresented Populations in Precision Medicine: A Federated Transfer Learning Approach](https://projecteuclid.org/journals/annals-of-applied-statistics/volume-17/issue-4/Targeting-underrepresented-populations-in-precision-medicine--A-federated-transfer/10.1214/23-AOAS1747.short). *Annals of Applied Statistics*. 17(4), 2970-2992, 2023.

**Sai Li**, Linjun Zhang, T. Tony Cai, and Hongzhe Li. [Estimation and inference in high-dimensional generalized linear models with knowledge transfer](https://www.tandfonline.com/doi/full/10.1080/01621459.2023.2184373). *Journal of the American Statistical Association*. 119(546), 1274-1285, 2024.

 Jianqiao Wang, **Sai Li**, and Hongzhe Li. [A unified approach to robust inference for genetic covariance](https://arxiv.org/abs/2106.04106). *Journal of the American Statistical Association(accepted)*. 2023.

**Sai Li**, T. Tony Cai, and Hongzhe Li. [Estimation and Inference with Proxy Data and its Genetic Applications](https://arxiv.org/abs/2201.03727). *Statistica Sinica(accepted)*. 2024.

Ziya Xu and **Sai Li**. [Leveraging Local Distributions in Mendelian Randomization: Uncertain Opinions are Invalid](https://arxiv.org/abs/2402.02329). *Statistica Sinica (accepted)*. 2024.

 **Sai Li**, Yisha Yao, and Cun-Hui Zhang.
Comment: [A Scale-Free Approach for False Discovery Rate Control in Generalized Linear Models](https://www.tandfonline.com/doi/abs/10.1080/01621459.2023.2224412). *Journal of the American Statistical Association(accepted)*. 2023.

**Sai Li**, Ritwik Mitra, and Cun-Hui Zhang.
[Comment: An adaptive resampling test for detecting the presence of significant predictors](http://dx.doi.org/10.1080/01621459.2015.1106404). *Journal of the American Statistical Association*. 110(512): 1455-1456. 2016.


**Sai Li** and Zijian Guo. [Causal inference for nonlinear outcomes with possibly invalid instrumentalvariables](http://arxiv.org/abs/2010.09922). *Technical report*. 2020.


Elynn Chen, Michael Jordan, **Sai Li**. [Transferred Q-learning](https://arxiv.org/abs/2202.04709). *submitted*. 2022.

**Sai Li** and Ting Ye. [A Focusing Framework for Testing Bi-Directional Causal Effects with GWAS Summary Data](https://arxiv.org/abs/2203.06887). *Submitted*. 2022.

&nbsp;

## Conference talks and service

 Concurrent session, Women in Statistics and Data Science 2020, online, ``Transfer learning in high-dimensional sparse regression'', 10/2020.
 
Session Chair, Modern Statistical Learning Methods, JSM 2020.
 
Contributed talks, JSM 2019 and JSM 2020. 

Invited talk, CMStatistics 2018, Pisa, Italy,``Debiasing the debiased Lasso with bootstrap'', 12/2018.

Poster presentation, Mendelian randomization in the age of large-scale accessible genomics data, Bristol, UK, ``Mendelian Randomization when many instruments are invalid: hierarchical empirical Bayes estimation'', 07/2017.

 Student paper competition, WNAR conference, Santa Fe, ``Mendelian Randomization when many instruments are invalid: hierarchical empirical Bayes estimation'', 06/17.


&nbsp;

## Teaching

**Instructor**:  
Statistical models and inference (PhD level), Fall 2021.

Statistical foundations of data science and AI (MS level), Fall 2021.

Introductory Statistics for Business (Undergrad), Summer 2016.


&nbsp;

## Awards

Travel Award, Conference on [Mendelian randomization in the age of large-scale accessible genomics data](https://www.mendelianrandomization.org.uk), 07/17.

Student Distinguished Written Paper Award, [WNAR conference](http://wnar.org), 06/17.

TA/GA Professional Development Fund, 06/15, 06/16.

Certificate of Excellence for attending 3rd Annual Interdisciplinary Quantitative Biology Boot
  Camp-drug discovery and development, 01/16. 




