---
title: "Research by topics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;

## High-dimensional estimation and inference

**Sai Li**. [Debiasing the debiased Lasso with bootstrap]( https://arxiv.org/abs/1711.03613). *Electronic Journal of Statistics*. 14(1): 2298-2337,2020. 

**Sai Li**, T. Tony Cai, and Hongzhe Li. [Inference for high-dimensional linear mixed-effects models: A quasi-likelihood approach](https://arxiv.org/abs/1907.06116). *Journal of the American Statistical Association*. 117(540): 1835-1846, 2022.

**Sai Li**, T. Tony Cai, and Hongzhe Li. [Estimation and Inference with Proxy Data and its Genetic Applications](https://arxiv.org/abs/2201.03727). *Statistica Sinica (accepted)*. 2024.




&nbsp;

## Transfer learning and domain generalization

**Sai Li** and Linjun Zhang. [Multi-dimensional domain generalization with low-rank structures](https://arxiv.org/abs/2309.09555). *Submitted*. 2023.

**Sai Li**, T. Tony Cai, and Hongzhe Li. [Transfer learning for high-dimensional linear regression: Prediction, estimation, and minimax optimality](https://academic.oup.com/jrsssb/article/84/1/149/7056104). *Journal of the Royal Statistical Society Series B*. 84: 149–173, 2022.

**Sai Li**, T. Tony Cai, and Hongzhe Li. [Transfer learning in large-scale graphical models with false discovery rate control](https://www.tandfonline.com/doi/abs/10.1080/01621459.2022.2044333). *Journal of the American Statistical Association*.118(543), 2171-2183, 2023.

**Sai Li**, Tianxi Cai, and Rui Duan. [Targeting Underrepresented Populations in Precision Medicine: A Federated Transfer Learning Approach](https://projecteuclid.org/journals/annals-of-applied-statistics/volume-17/issue-4/Targeting-underrepresented-populations-in-precision-medicine--A-federated-transfer/10.1214/23-AOAS1747.short). *Annals of Applied Statistics*. 17(4), 2970-2992, 2023.

**Sai Li**, Linjun Zhang, T. Tony Cai, and Hongzhe Li. [Estimation and inference in high-dimensional generalized linear models with knowledge transfer](https://www.tandfonline.com/doi/full/10.1080/01621459.2023.2184373). *Journal of the American Statistical Association*. 119(546), 1274-1285, 2024.

**Sai Li** and Linjun Zhang. [Multi-dimensional domain generalization with low-rank structures](https://www.tandfonline.com/doi/full/10.1080/01621459.2025.2471055?src=exp-la). *Journal of the American Statistical Association(accepted)*. 2025.


&nbsp;

## Causal inference

**Sai Li** and Ting Ye. [A Focusing Framework for Testing Bi-Directional Causal Effects with GWAS Summary Data](https://arxiv.org/abs/2203.06887). *Journal of the Royal Statistical Society: Series B (accepted)*. 2024.

Ziya Xu and **Sai Li**. [Leveraging Local Distributions in Mendelian Randomization: Uncertain Opinions are Invalid](https://arxiv.org/abs/2402.02329). *Statistica Sinica (accepted)*. 2024. (with my student)

Wei Li, Rui Duan, and **Sai Li**. [Discovery and inference of possibly bi-directional causal relationships with invalid instrumental variables](https://arxiv.org/abs/2407.11646). *Submitted*. 2024.


**Sai Li** and Zijian Guo. [Causal inference for nonlinear outcomes with possibly invalid instrumentalvariables](http://arxiv.org/abs/2010.09922). *Technical report*. 2020.


**Sai Li**. 
 [Mendelian Randomization when many instruments are invalid: hierarchical empirical Bayes estimation](https://arxiv.org/abs/1706.01389). *Technical report*. 2017.

&nbsp;

## Other collaborative works
Zhanrui Cai, **Sai Li**, Xintao Xia, and Linjun Zhang. [Differentially Private Estimation and Inference in High-Dimensional Regression with FDR Control](https://arxiv.org/abs/2310.16260). *(submitted).* 2024. (alphabetical order)

Jianqiao Wang, **Sai Li**, and Hongzhe Li. [A unified approach to robust inference for genetic covariance](https://arxiv.org/abs/2106.04106). *Journal of the American Statistical Association (accepted)*. 2023.

**Sai Li**, Yisha Yao, and Cun-Hui Zhang.
Comment: A Scale-Free Approach for False Discovery Rate Control in Generalized Linear Models. *Journal of the American Statistical Association(accepted)*. 2023.

Huaxiu Yao, Yu Wang, **Sai Li**, Linjun Zhang, Weixin Liang, James Zou, and Chelsea Finn. [ Improving out-of-distribution robustness via selective augmentation](https://arxiv.org/abs/2201.00299). *International Conference of Machine Learning*. 2022.


**Sai Li**, Ritwik Mitra, and Cun-Hui Zhang.
[Comment: An adaptive resampling test for detecting the presence of significant predictors](   http://dx.doi.org/10.1080/01621459.2015.1106404). *Journal of the American Statistical Association*. 110(512): 1455-1456. 2016.




